### PR TITLE
Added cursor as a Pointer

### PR DESCRIPTION
**Pull request by Devenkapoor7303**
I have added a anchor element having a text Decoration equal to none. So basically it is acting as a pointer.

### CODE REVIEW

**Comment by sushrut111** [comment]
That is cool. I would like to have full block which says 
"Confused if you should see a doctor?
Take the quiz to know. (Click me!)"
to have a pointer when mouse hovers over it, including the rectangle in the background.

**Comment by Devenkapoor7303** [comment]
Okay I will do that.

**Comment by Devenkapoor7303** [comment]
@sushrut111 so basically u want this thing all over the yellow block so that whenever someone hovers over the yellow block it will convert into the cursor as a pointer.

**Comment by sushrut111** [comment]
That is correct @Devenkapoor7303

**Comment by Devenkapoor7303** [comment]
Hey @sushrut111 I made the changes can u please check this out?

**Pull request closed without merging**
