### PR TITLE
improved Important links section

### PR DESCRIPTION
**Pull request by PiyushNadoda**

### CODE REVIEW

**Comment by sushrut111** [comment]
@PiyushNadoda Can you please merge main/master branch to you branch?

**Review by sushrut111 — APPROVED** [review]

**Comment by PiyushNadoda** [comment]
@sushrut111 I have solved the conflicts. you can merge now.

**Comment by sushrut111** [comment]
@PiyushNadoda Looks like while resolving conflicts you have dropped the newer changes. Could you please look at the deployed the version at "https://sushrut111.github.io/corona-virus-questionnaire/" and make sure the changes are available in your local deployment? (The change that we are missing here is button like feel on the yellow banner at which says "Take the quiz to know"

**Comment by PiyushNadoda** [comment]
Conflict solved with latest changes.

**Comment by sushrut111** [comment]
Hey @PiyushNadoda 
Just checked, 
image


The names at the bottom are not supposed to be links.

**Comment by PiyushNadoda** [comment]
Sorry I didn't noticed that. I'll fix it.

**Pull request closed without merging**
