### PR TITLE
ESLint and Pretttier added.

### PR DESCRIPTION
**Pull request by joshi-kaushal**
## Description:
ESLint and Prettier added to the project. 
ESLint errors/warnings can be reviewed with `npm run lint` command.
For fixing possible errors, `npm run lint:fix` can be used.

### I have ignored these warnings/errors because I think this must have some future use:
1.  `/src/api/questions` is imported but not used (no-unused-vars)
2. `<prop-name>` is missing prop validation (react\prop-types)
3. `<variable>` was used before it was defined (no-use-before-define)
4. Do not use Array index in keys (react/no-array-index-key)
5. Identifier `<variable>` is not in camel case (camelcase)

### Rules ignored in eslint config file:
1. react/jsx-filename-extension
2. no-console
3. button-has-type
4. react/button-has-type

### CODE REVIEW

**Comment by sushrut111** [comment]
@joshi-kaushal 
I am not able to run `npm run lint` on a windows machine. Could you look at it?
For starter, you might want to add npx before eslint in the scripts in package.json.

Make sure things work well on windows platform. 

Also, can you please remove package-lock.json from commits and add it to .gitignore?

I really appreciate your help for this. I am adding the appropriate label to this PR so that it is counted for Hacktoberfest.

**Comment by joshi-kaushal** [comment]
If you're talking about `ELIFECYCLE` error at the end, it's related to how NPM scripts are executed in node JS. I was trying to figure out the issue myself but found nothing useful. It's working fine on WSL but not on Git Bash or Powershell. 

This answer explains my point well: https://github.com/eslint/eslint/issues/7933#issuecomment-273269297
Also look at these:
- https://github.com/eslint/eslint/issues/7933
- https://github.com/eslint/eslint/issues/7402

If you are having some other issue, please provide relevant screenshots and info so I can work on this.

**Comment by joshi-kaushal** [comment]
Hello @sushrut111, did you check?

**Comment by joshi-kaushal** [comment]
Hi @sushrut111, if there is anything more that I can improve, tell me now so I can finish it before the 31st.

If you're okay with this, please accept the PR.
If you're confused, you can make a new branch and merge it.

Thankyou!

**Comment by sushrut111** [comment]
Hey @joshi-kaushal  i already have tagged this PR with required tag to be accepted for hacktoberfest. You should be good. I did not get time to really check it better.

**Comment by joshi-kaushal** [comment]
Hello @sushrut111, I have realized this PR is still pending. Can we settle it down?

**Pull request closed without merging**
