### PR TITLE
💄 Improved Important link section

### PR DESCRIPTION
**Pull request by piyush-nadoda**

### CODE REVIEW

**Comment by PiyushNadoda** [comment]
@sushrut111  can you check this ?

**Review by sushrut111 — APPROVED** [review]

**Comment by PiyushNadoda** [comment]
can you merge it ?

**Comment by sushrut111** [comment]
Merged and deployed: https://sushrut111.github.io/corona-virus-questionnaire/

**Comment by sushrut111** [comment]
Thank you for your contribution

**Pull request merged**
